version: "3"

services:
  database:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - memo-db:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 5000:5000

volumes:
  memo-db: